app:
  kafka-configs:
    bootstrap-servers: localhost:9093
    kafka-consumer-group: test
    links-topic-name: links
    pages-topic-name: pages
  crawler-configs:
    in-memory-link-queue-size: 100
    in-memory-page-queue-size: 100
    politeness-duration-in-seconds: 60
    max-in-memory-politeness-records: 10000
    request-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
    request-timeout-milliseconds: 15000
    english-language-detector-minimum-score: 0.90

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: linksDatabase
      username: root
      password: password
