app:
  in-memory-link-queue-size: 100
  kafka-configs:
    bootstrap-servers: localhost:9093
    kafka-consumer-group: test
    links-topic-name: links
  crawler-configs:
    politeness-duration-in-seconds: 60
    max-in-memory-politeness-records: 10000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: links_database
      username: root
      password: password
