app:
  anchors-parquet-directory: /anchors-parquet
  keywords-parquet-directory: /keywords-parquet
  maximum-graph-edges: 5000000
  result-directory-path: /graph
  spark-configs:
    spark-master-address: spark-master:7077
    spark-configs:
      spark.executor.memory: 6g
      spark.driver.memory: 2g
  hadoop-configs:
    hadoop-name-node-hostname: namenode
    hadoop-name-node-port: 9000
